"""Run benchmarks and write results/ (JSON per benchmark, RESULTS.md, figures/*.png)."""
from __future__ import annotations

import json
import time
from pathlib import Path

from ..corpus import data_dir
from . import adfa, opa_equiv, perf, posture, provenance, pss, runtime, scans
from .meta import provenance as run_provenance

BENCHES = {"pss": pss, "posture": posture, "provenance": provenance, "scans": scans, "runtime": runtime,
           "adfa": adfa, "opa": opa_equiv, "perf": perf}
NEEDS = {"pss": "pss/testdata", "posture": "manifests/index.json", "provenance": "provenance/provenance.json",
         "scans": "scans", "runtime": "tetragon", "adfa": "adfa", "opa": "manifests/index.json", "perf": "manifests/index.json"}


def _strip(d):
    if isinstance(d, dict):
        return {k: _strip(v) for k, v in d.items() if not k.startswith("_")}
    return d


def _source_line(path: Path) -> str:
    """One-line provenance note for a RESULTS.md section, from the JSON's ``provenance`` block."""
    try:
        p = json.loads(path.read_text(encoding="utf-8")).get("provenance") or {}
    except (OSError, ValueError):
        return ""
    if not p:
        return ""
    return ("\n\n_Source: " + (p.get("source_run") or "local run") + f", commit `{(p.get('commit') or '?')[:7]}`"
            + (" (uncommitted code changes)" if p.get("code_modified") else "")
            + (f", dataset manifest `{p['dataset_manifest_sha256'][:12]}`" if p.get("dataset_manifest_sha256") else "")
            + "._")


def run(names: list[str] | None = None, root: Path | None = None, out: Path = Path("results")) -> dict:
    root = root or data_dir()
    out.mkdir(parents=True, exist_ok=True)
    done = {}
    prov = run_provenance(root)
    for name in names or list(BENCHES):
        if not (root / NEEDS[name]).exists():
            print(f"[skip] {name}: {root / NEEDS[name]} missing")
            continue
        if hasattr(BENCHES[name], "available") and not BENCHES[name].available():
            print(f"[skip] {name}: opa binary not found")
            continue
        t = time.perf_counter()
        r = BENCHES[name].run(root)
        (out / f"{name}.json").write_text(json.dumps({**_strip(r), "provenance": prov}, indent=1, default=str),
                                          encoding="utf-8")
        (out / f"{name}.md").write_text(BENCHES[name].markdown(r) + "\n", encoding="utf-8")
        done[name] = r
        print(f"[ok]   {name} ({time.perf_counter() - t:.1f}s)")
    if not done:
        print("[warn] no benchmark ran (set STRATUM_DATA or run scripts/download_all.py)")
    try:
        from .figures import render
        render(done, out / "figures")
    except ImportError:
        print("[info] matplotlib not installed - figures skipped")
    parts = [(out / f"{n}.md").read_text(encoding="utf-8").rstrip("\n") + _source_line(out / f"{n}.json")
             for n in BENCHES if (out / f"{n}.md").exists()]
    (out / "RESULTS.md").write_text(
        "# STRATUM benchmark results\n\nGenerated by `python -m stratum bench`; each section names the run, commit "
        "and dataset manifest it came from (the `provenance` block of its JSON). See README for datasets and protocol. "
        "The live CI, Kim et al. reproduction and container syscall results come from GitHub Actions runs and are in "
        "live.md, kim_lstm.md and container_syscalls.md.\n\n" + "\n\n".join(parts) + "\n", encoding="utf-8")
    return done
