"""Run benchmarks and write results/ (JSON per benchmark, RESULTS.md, figures/*.png)."""
from __future__ import annotations

import json
import time
from pathlib import Path

from ..corpus import data_dir
from . import adfa, opa_equiv, perf, posture, provenance, pss, runtime, scans

BENCHES = {"pss": pss, "posture": posture, "provenance": provenance, "scans": scans, "runtime": runtime,
           "adfa": adfa, "opa": opa_equiv, "perf": perf}
NEEDS = {"pss": "pss/testdata", "posture": "manifests/index.json", "provenance": "provenance/provenance.json",
         "scans": "scans", "runtime": "tetragon", "adfa": "adfa", "opa": "manifests/index.json", "perf": "manifests/index.json"}


def _strip(d):
    if isinstance(d, dict):
        return {k: _strip(v) for k, v in d.items() if not k.startswith("_")}
    return d


def run(names: list[str] | None = None, root: Path | None = None, out: Path = Path("results")) -> dict:
    root = root or data_dir()
    out.mkdir(parents=True, exist_ok=True)
    done = {}
    for name in names or list(BENCHES):
        if not (root / NEEDS[name]).exists():
            print(f"[skip] {name}: {root / NEEDS[name]} missing")
            continue
        if hasattr(BENCHES[name], "available") and not BENCHES[name].available():
            print(f"[skip] {name}: opa binary not found")
            continue
        t = time.perf_counter()
        r = BENCHES[name].run(root)
        (out / f"{name}.json").write_text(json.dumps(_strip(r), indent=1, default=str), encoding="utf-8")
        (out / f"{name}.md").write_text(BENCHES[name].markdown(r) + "\n", encoding="utf-8")
        done[name] = r
        print(f"[ok]   {name} ({time.perf_counter() - t:.1f}s)")
    if not done:
        print("[warn] no benchmark ran (set STRATUM_DATA or run scripts/download_all.py)")
    try:
        from .figures import render
        render(done, out / "figures")
    except ImportError:
        print("[info] matplotlib not installed - figures skipped")
    parts = [(out / f"{n}.md").read_text(encoding="utf-8") for n in BENCHES if (out / f"{n}.md").exists()]
    (out / "RESULTS.md").write_text("# STRATUM benchmark results\n\nGenerated by `python -m stratum bench`. "
                                    "See README for datasets and protocol.\n\n" + "\n\n".join(parts),
                                    encoding="utf-8")
    return done
