"""Regenerate docs pages that mirror README sections (getting started, evaluation, limitations)."""
from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
BLOB = "https://github.com/rakshit-737/stratum/blob/main/"


def main() -> None:
    r = (ROOT / "README.md").read_text(encoding="utf-8")

    def sec(title: str) -> str:
        m = re.search(r"^## " + re.escape(title) + r"\n(.*?)(?=^## )", r, re.S | re.M)
        return m.group(1)

    def fix(t: str) -> str:
        t = re.sub(r'<img src="results/figures/([^"]+)" width="(\d+)%" alt="([^"]*)">',
                   r'![\3](figures/\1){ width="\2%" }', t)
        t = t.replace("](docs/adr/", "](adr/").replace("](docs/figures/", "](figures/")
        t = re.sub(r"\]\(docs/([a-z-]+\.md)\)", r"](\1)", t)
        t = t.replace("](docs/datasets.md)", "](datasets.md)")
        return re.sub(r"\]\(((?:results|benchmarks|\.github)/[^)]*)\)", rf"]({BLOB}\1)", t)

    # docs/index.md is hand-written (landing page) except its headline table, which is copied from the README
    # between the markers so the two cannot diverge.
    idx = (DOCS / "index.md").read_text(encoding="utf-8")
    start, end = "<!-- headline:start (generated by scripts/sync_docs.py) -->", "<!-- headline:end -->"
    if start in idx and end in idx:
        table = "\n".join(ln for ln in sec("Headline results").strip().splitlines() if ln.startswith("|"))
        idx = idx[:idx.index(start) + len(start)] + "\n" + fix(table) + "\n" + idx[idx.index(end):]
        (DOCS / "index.md").write_text(idx, encoding="utf-8")
    (DOCS / "getting-started.md").write_text(fix(
        "# Getting started\n\n## Install and first run\n" + sec("Quickstart") + "## Reproducing the results\n"
        + sec("Reproducing the results") + "## Docker\n\n```bash\n"
        "docker run --rm -p 127.0.0.1:8000:8000 ghcr.io/rakshit-737/stratum:latest   # synthetic source\n"
        "docker build -t stratum . && docker run --rm -p 127.0.0.1:8000:8000 -e STRATUM_SOURCE=live stratum  # live CI replay (main)\n"
        "NEO4J_PASSWORD='choose-one' docker compose up                  # API + Neo4j 5 (compose refuses to start without it)\n"
        "```\n\nThe image is built for linux/amd64 only; on ARM hosts (Apple silicon, Graviton) add "
        "`--platform linux/amd64`. `NEO4J_PASSWORD` can also go in a `.env` file next to `docker-compose.yml`.\n"),
        encoding="utf-8")
    detail = r[r.index("## Results in detail") + len("## Results in detail"):r.index("## Prior art")]
    (DOCS / "evaluation.md").write_text(fix(
        "# Evaluation\n\nThe numbers come from `python -m stratum bench` on the real corpus (`results/RESULTS.md`), "
        "the live CI job (`results/live.md`), the Kim et al. reproduction (`results/kim_lstm.md`) and the container "
        "syscall workflow (`results/container_syscalls.md`); each result file records the run and commit that produced "
        "it. Proportions carry Wilson 95% intervals and model scores bootstrap or corrected-t intervals; counts that are "
        "deterministic or fully observed (posture findings, scan totals, the provenance funnel) are reported as counts."
        "\n\n" + sec("Headline results") + "\n## Results in detail\n" + detail
        + "\n## Prior art\n" + sec("Prior art and how this differs")), encoding="utf-8")
    (DOCS / "limitations.md").write_text(fix(
        "# Limitations and roadmap\n\n## Limitations\n" + sec("Limitations") + "## Roadmap\n" + sec("Roadmap")),
        encoding="utf-8")
    (DOCS / "figures").mkdir(exist_ok=True)
    for png in (ROOT / "results" / "figures").glob("*.png"):
        shutil.copy2(png, DOCS / "figures" / png.name)


if __name__ == "__main__":
    main()
